version: "3.3"

services:
  ica_db_postgres:
    image: postgres:14.1-alpine
    restart: ${DOCKER_RESTART}
    env_file: ".env"
    hostname: ${POSTGRES_HOST}
    container_name: ${POSTGRES_CONTAINER}
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:3000"
    volumes:
      - ica-db-data:/var/lib/postgresql/data
    networks:
      - ica-network

volumes:
  ica-db-data:

    null
networks:
  ica-network:
    driver: bridge